---
- name: Disable services
  systemd:
    name: "docker"
    state: stopped
    enabled: no

- name: Remove docker
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-ce-rootless-extras
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Remove docker
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-ce-rootless-extras
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Remove data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/containerd
    - /etc/docker
    - "{{ project_dir}}"

- name: daemon_reload
  systemd:
    daemon_reload: yes
